# $1 = imagenetbert13epochs
python inception_score.py ../outputs/samples2x6-l23-$1-edentate/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-clock/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-breathing_device/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-summer_squash/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-pan/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-hawk/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-pelagic_bird/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-strongbox/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-shark/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-turnstone/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-machine/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-fabric/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-spitz/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-door/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-terrier/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-eraser/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-farm_building/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-theater/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-mastiff/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-pistol/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-trouser/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-newt/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-wall_unit/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-pinscher/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-coffee_maker/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-clip/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-sea_turtle/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-place_of_worship/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-cabinet/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-lamp/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-finch/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-egret/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-building/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-toy_dog/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-adornment/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-toothed_whale/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-ball/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-visual_signal/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-plant/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-digital_computer/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-aquatic_bird/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-fruit/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-fastener/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-electronic_device/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-sweater/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-boa/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-dog/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-lever/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-wagon/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-top/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-opener/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-paper/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-home_appliance/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-appliance/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-associate/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-food/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-anseriform_bird/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-crustacean/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-contestant/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-musical_instrument/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-feline/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-mask/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-cat/samples/
python inception_score.py ../outputs/samples2x6-l23-$1-vegetable/samples/