# $1 = imagenetbert13epochs
python fid_score.py ../outputs/samples2x6-l23-$1-edentate/samples/ ../classes-23/edentate/
python fid_score.py ../outputs/samples2x6-l23-$1-clock/samples/ ../classes-23/clock/
python fid_score.py ../outputs/samples2x6-l23-$1-breathing_device/samples/ ../classes-23/breathing_device/
python fid_score.py ../outputs/samples2x6-l23-$1-summer_squash/samples/ ../classes-23/summer_squash/
python fid_score.py ../outputs/samples2x6-l23-$1-pan/samples/ ../classes-23/pan/
python fid_score.py ../outputs/samples2x6-l23-$1-hawk/samples/ ../classes-23/hawk/
python fid_score.py ../outputs/samples2x6-l23-$1-pelagic_bird/samples/ ../classes-23/pelagic_bird/
python fid_score.py ../outputs/samples2x6-l23-$1-strongbox/samples/ ../classes-23/strongbox/
python fid_score.py ../outputs/samples2x6-l23-$1-shark/samples/ ../classes-23/shark/
python fid_score.py ../outputs/samples2x6-l23-$1-turnstone/samples/ ../classes-23/turnstone/
python fid_score.py ../outputs/samples2x6-l23-$1-machine/samples/ ../classes-23/machine/
python fid_score.py ../outputs/samples2x6-l23-$1-fabric/samples/ ../classes-23/fabric/
python fid_score.py ../outputs/samples2x6-l23-$1-spitz/samples/ ../classes-23/spitz/
python fid_score.py ../outputs/samples2x6-l23-$1-door/samples/ ../classes-23/door/
python fid_score.py ../outputs/samples2x6-l23-$1-terrier/samples/ ../classes-23/terrier/
python fid_score.py ../outputs/samples2x6-l23-$1-eraser/samples/ ../classes-23/eraser/
python fid_score.py ../outputs/samples2x6-l23-$1-farm_building/samples/ ../classes-23/farm_building/
python fid_score.py ../outputs/samples2x6-l23-$1-theater/samples/ ../classes-23/theater/
python fid_score.py ../outputs/samples2x6-l23-$1-mastiff/samples/ ../classes-23/mastiff/
python fid_score.py ../outputs/samples2x6-l23-$1-pistol/samples/ ../classes-23/pistol/
python fid_score.py ../outputs/samples2x6-l23-$1-trouser/samples/ ../classes-23/trouser/
python fid_score.py ../outputs/samples2x6-l23-$1-newt/samples/ ../classes-23/newt/
python fid_score.py ../outputs/samples2x6-l23-$1-wall_unit/samples/ ../classes-23/wall_unit/
python fid_score.py ../outputs/samples2x6-l23-$1-pinscher/samples/ ../classes-23/pinscher/
python fid_score.py ../outputs/samples2x6-l23-$1-coffee_maker/samples/ ../classes-23/coffee_maker/
python fid_score.py ../outputs/samples2x6-l23-$1-clip/samples/ ../classes-23/clip/
python fid_score.py ../outputs/samples2x6-l23-$1-sea_turtle/samples/ ../classes-23/sea_turtle/
python fid_score.py ../outputs/samples2x6-l23-$1-place_of_worship/samples/ ../classes-23/place_of_worship/
python fid_score.py ../outputs/samples2x6-l23-$1-cabinet/samples/ ../classes-23/cabinet/
python fid_score.py ../outputs/samples2x6-l23-$1-lamp/samples/ ../classes-23/lamp/
python fid_score.py ../outputs/samples2x6-l23-$1-finch/samples/ ../classes-23/finch/
python fid_score.py ../outputs/samples2x6-l23-$1-egret/samples/ ../classes-23/egret/
python fid_score.py ../outputs/samples2x6-l23-$1-building/samples/ ../classes-23/building/
python fid_score.py ../outputs/samples2x6-l23-$1-toy_dog/samples/ ../classes-23/toy_dog/
python fid_score.py ../outputs/samples2x6-l23-$1-adornment/samples/ ../classes-23/adornment/
python fid_score.py ../outputs/samples2x6-l23-$1-toothed_whale/samples/ ../classes-23/toothed_whale/
python fid_score.py ../outputs/samples2x6-l23-$1-ball/samples/ ../classes-23/ball/
python fid_score.py ../outputs/samples2x6-l23-$1-visual_signal/samples/ ../classes-23/visual_signal/
python fid_score.py ../outputs/samples2x6-l23-$1-plant/samples/ ../classes-23/plant/
python fid_score.py ../outputs/samples2x6-l23-$1-digital_computer/samples/ ../classes-23/digital_computer/
python fid_score.py ../outputs/samples2x6-l23-$1-aquatic_bird/samples/ ../classes-23/aquatic_bird/
python fid_score.py ../outputs/samples2x6-l23-$1-fruit/samples/ ../classes-23/fruit/
python fid_score.py ../outputs/samples2x6-l23-$1-fastener/samples/ ../classes-23/fastener/
python fid_score.py ../outputs/samples2x6-l23-$1-electronic_device/samples/ ../classes-23/electronic_device/
python fid_score.py ../outputs/samples2x6-l23-$1-sweater/samples/ ../classes-23/sweater/
python fid_score.py ../outputs/samples2x6-l23-$1-boa/samples/ ../classes-23/boa/
python fid_score.py ../outputs/samples2x6-l23-$1-dog/samples/ ../classes-23/dog/
python fid_score.py ../outputs/samples2x6-l23-$1-lever/samples/ ../classes-23/lever/
python fid_score.py ../outputs/samples2x6-l23-$1-wagon/samples/ ../classes-23/wagon/
python fid_score.py ../outputs/samples2x6-l23-$1-top/samples/ ../classes-23/top/
python fid_score.py ../outputs/samples2x6-l23-$1-opener/samples/ ../classes-23/opener/
python fid_score.py ../outputs/samples2x6-l23-$1-paper/samples/ ../classes-23/paper/
python fid_score.py ../outputs/samples2x6-l23-$1-home_appliance/samples/ ../classes-23/home_appliance/
python fid_score.py ../outputs/samples2x6-l23-$1-appliance/samples/ ../classes-23/appliance/
python fid_score.py ../outputs/samples2x6-l23-$1-associate/samples/ ../classes-23/associate/
python fid_score.py ../outputs/samples2x6-l23-$1-food/samples/ ../classes-23/food/
python fid_score.py ../outputs/samples2x6-l23-$1-anseriform_bird/samples/ ../classes-23/anseriform_bird/
python fid_score.py ../outputs/samples2x6-l23-$1-crustacean/samples/ ../classes-23/crustacean/
python fid_score.py ../outputs/samples2x6-l23-$1-contestant/samples/ ../classes-23/contestant/
python fid_score.py ../outputs/samples2x6-l23-$1-musical_instrument/samples/ ../classes-23/musical_instrument/
python fid_score.py ../outputs/samples2x6-l23-$1-feline/samples/ ../classes-23/feline/
python fid_score.py ../outputs/samples2x6-l23-$1-mask/samples/ ../classes-23/mask/
python fid_score.py ../outputs/samples2x6-l23-$1-cat/samples/ ../classes-23/cat/
python fid_score.py ../outputs/samples2x6-l23-$1-vegetable/samples/ ../classes-23/vegetable/