# $1 = imagenetbert13epochs
python fid_score.py ../outputs/samples2x6-$1-hen/samples/ ../classes/hen/
python fid_score.py ../outputs/samples2x6-$1-traffic_light/samples/ ../classes/traffic_light/
python fid_score.py ../outputs/samples2x6-$1-dock/samples/ ../classes/dock/
python fid_score.py ../outputs/samples2x6-$1-monarch/samples/ ../classes/monarch/
python fid_score.py ../outputs/samples2x6-$1-gar/samples/ ../classes/gar/
python fid_score.py ../outputs/samples2x6-$1-chow/samples/ ../classes/chow/
python fid_score.py ../outputs/samples2x6-$1-whistle/samples/ ../classes/whistle/
python fid_score.py ../outputs/samples2x6-$1-killer_whale/samples/ ../classes/killer_whale/
python fid_score.py ../outputs/samples2x6-$1-diamondback/samples/ ../classes/diamondback/
python fid_score.py ../outputs/samples2x6-$1-malinois/samples/ ../classes/malinois/
python fid_score.py ../outputs/samples2x6-$1-starfish/samples/ ../classes/starfish/
python fid_score.py ../outputs/samples2x6-$1-rocking_chair/samples/ ../classes/rocking_chair/
python fid_score.py ../outputs/samples2x6-$1-bee/samples/ ../classes/bee/
python fid_score.py ../outputs/samples2x6-$1-liner/samples/ ../classes/liner/
python fid_score.py ../outputs/samples2x6-$1-cradle/samples/ ../classes/cradle/
python fid_score.py ../outputs/samples2x6-$1-Irish_terrier/samples/ ../classes/Irish_terrier/